---
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.19"
  amd64: "ghcr.io/home-assistant/amd64-base:3.19"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: SeaweedFS"
  org.opencontainers.image.description: "SeaweedFS S3-compatible distributed object storage"
  org.opencontainers.image.source: "https://github.com/kalw/hassio-addons"
  org.opencontainers.image.licenses: "MIT"
args:
  SEAWEEDFS_VERSION: "4.34"
