---
build_from:
  aarch64: "ghcr.io/hassio-addons/base-aarch64:21.0.0"
  amd64: "ghcr.io/hassio-addons/base-amd64:21.0.0"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: SeaweedFS"
  org.opencontainers.image.description: "SeaweedFS S3-compatible distributed object storage"
  org.opencontainers.image.source: "https://github.com/kalw/hassio-addons"
  org.opencontainers.image.licenses: "MIT"
args:
  SEAWEEDFS_VERSION: "4.34"
